---
# See https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  go: '1.23' # Depends on the version with which golangci-lint was built.
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/get-eventually/go-eventually)
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: prefix(flugg.app/flugg)
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport  # https://github.com/go-critic/go-critic/issues/845
  misspell:
    locale: US
  lll:
    line-length: 160
  tagliatelle:
    case:
      rules:
        json: snake
  unused:
    exported-fields-are-used: false
  unparam:
    check-exported: true
  gomodguard:
    blocked:
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
  varnamelen:
    ignore-names:
      - err
      - tc  # For test cases, like `for _, tc := range testcases`
      - id

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - exhaustruct
    - copyloopvar
    - funlen
    - gci
    - gochecknoinits
    # - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox
    - gofumpt
    - goimports
    - gomodguard
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    # - ifshort
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wsl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
