---
name: Setup Go
description: |
  Sets up the Go toolchain cache for faster execution.
runs:
  using: composite
  steps:
    - name: Setup cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ github.workflow }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.workflow }}-golang-
