---
name: Setup Go
description: |
  Sets up the Go toolchain cache for faster execution.
runs:
  using: composite
  steps:
    - name: Setup cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ github.workflow }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.workflow }}-golang-
