---
name: Setup Go
description: |
  Sets up the Go toolchain cache for faster execution.
runs:
  using: composite
  steps:
    - name: Setup cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ github.workflow }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.workflow }}-golang-
