---
name: Setup Go
description: |
  Sets up the Go toolchain cache for faster execution.
runs:
  using: composite
  steps:
    - name: Setup cache
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ github.workflow }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.workflow }}-golang-
