---
name: Setup Go
description: |
  Sets up the Go toolchain cache for faster execution.
runs:
  using: composite
  steps:
    - name: Setup cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ github.workflow }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.workflow }}-golang-
