---
name: Setup Nix and direnv
description: |
  Sets up the Nix package manager and direnv to use the same packages
  vendored through Nix for local development.
inputs:
  github_token:
    description: 'Github Access Token'
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix package manager
      uses: DeterminateSystems/nix-installer-action@c723f3a885e3f1d866d91f4f0c33dd44b1fc7c60 # v18
      with:
        extra-conf: |
          experimental-features = nix-command flakes
    - name: Set up Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9
