name: Main Workflow
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        image: postgres:12
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up Go
        uses: ./.github/actions/setup-go
      # Used for Firestore integration tests
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'beta,cloud-firestore-emulator'
      - name: Retrieve Google Cloud info
        run: gcloud info
      - name: Start Google Cloud Firestore emulator
        run: gcloud beta emulators firestore start --host-port=0.0.0.0:9191 &
      - name: Run tests
        run: make run-tests
        env:
          FIRESTORE_EMULATOR_HOST: '[::1]:9191'
          GOOGLE_PROJECT_ID: test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./**/*.out
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.1
        # NOTE: we don't care if SonarCloud analysis fail, as we mainly use it
        # for code coverage tracking.
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: ./.github/actions/setup-go
      - name: Set up golangci-lint
        uses: ./.github/actions/setup-golangci-lint
      - name: Run golangci-lint
        run: GOLANGCI_LINT_FLAGS=--out-format=github-actions make run-linter
