name: Main Workflow
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        image: postgres:12
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Run tests
      run: make run-tests
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: ./**/*.out
    # NOTE: SonarCloud doesn't support Go 1.18 syntax yet, so I'm disabling this for now.
    #
    # Issue: https://jira.sonarsource.com/browse/SONARSLANG-552
    #
    # - name: Analyze with SonarCloud
    #   uses: sonarsource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  golangci-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      # NOTE: golangci-lint doesn't support Go workspaces properly, so we need to specify
      # the paths explicitly.
      #
      # Issue: https://github.com/golangci/golangci-lint/issues/2654
      #
      - name: Run golangci-lint (core)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./core
          args: -c ../.golangci.yml
      - name: Run golangci-lint (serdes)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./serdes
          args: -c ../.golangci.yml
      - name: Run golangci-lint (postgres)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./postgres
          args: -c ../.golangci.yml

