name: Main Workflow
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        image: postgres:12
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up Go
        uses: ./.github/actions/setup-go
      - name: Run tests
        run: make run-tests
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./**/*.out
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1.8
        # NOTE: we don't care if SonarCloud analysis fail, as we mainly use it
        # for code coverage tracking.
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: ./.github/actions/setup-go
      - name: Set up golangci-lint
        uses: ./.github/actions/setup-golangci-lint
      - name: Run golangci-lint
        run: GOLANGCI_LINT_FLAGS=--out-format=github-actions make run-linter
