---
name: Release

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    permissions:
      # NOTE: necessary to apply the git tag.
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # Using this to pick up the latest tag.
          fetch-depth: 0
      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@778d1d5b7af80aa43f50104116b8363e7fc0d1ef # v1
        with:
          token: ${{ github.token }}
          branch: main
          minorList: 'major, breaking'
          patchList: 'feat, fix, bugfix, perf, refactor, test, tests, doc, docs'
      - name: Push new version tag
        uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72 # v1
        if: ${{ contains(github.ref, 'main') }}  # only push tags if on main branch.
        with:
          tag: ${{ steps.semver.outputs.next }}
          tag_exists_error: false
          force_push_tag: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
