---
name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up Nix system
        uses: ./.github/actions/nix-setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: ./.github/actions/go-setup # NOTE: used for caching only.
      - name: Run 'make go.test'
        run: make go.test
        shell: nix develop --quiet -c bash -e {0}
      - name: Upload coverage report
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          verbose: true
          fail_ci_if_error: true
